foreground              #FFFFFF
background              #403728
selection_foreground    #403728
selection_background    #FFFFFF
cursor                  #9C7348 
cursor_text_color       #FFFFFF

active_tab_foreground     #403728
active_tab_background     #6D4C31
inactive_tab_foreground   #6D4C31
inactive_tab_background   #403728

# black
color0      #524229
color8      #8F7A57

# red
color1      #FFE6CC
color9      #F0CEAA

# green
color2      #FFFBCC
color10     #F0EAAA

# yellow
color3      #FFE3CC
color11     #F0C9AA

# blue
color4      #E6C99A
color12     #E6C99A

# magenta
color5      #E6DF9A
color13     #E6DF9A

# cyan
color6      #E6BC9A
color14     #E6BC9A

# white
color7      #FFE6CC
color15     #F0CEAA
