# █░█ █▄█ █▀█ █▀█ █ █▀▄ █░░ █▀▀
# █▀█ ░█░ █▀▀ █▀▄ █ █▄▀ █▄▄ ██▄

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 5 分钟无操作 -> 熄屏
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 10 分钟无操作 -> 锁屏
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}
