# █░█ █▄█ █▀█ █▀█ █ █▀▄ █░░ █▀▀
# █▀█ ░█░ █▀▀ █▀▄ █ █▄▀ █▄▄ ██▄

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 5 分钟无操作 -> 锁屏 (hyprlock grace=300, 前 5 分钟免密)
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 15 分钟无操作 -> 熄屏
listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
